server:
  port: 8443
  forward-headers-strategy: native

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  spring:
    security:
      oauth2:
        client:
          registration:
            kakao:
              client-id: ${KAKAO_CLIENT_ID}
              client-secret: ${KAKAO_CLIENT_SECRET}
              redirect-uri: ${OAUTH2_REDIRECT_URI}
              client-authentication-method: client_secret_post
              authorization-grant-type: authorization_code
              scope:
                - profile_nickname
              client-name: Kakao

          provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id

  mail:
    host: smtp.gmail.com
    port: 587
    username: jisung494@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cache:
    cache-names: weatherRecommendation  # 사용할 캐시 이름 정의
    caffeine:
      spec: maximumSize=1000, expireAfterWrite=1h  # 캐시 최대 1000개, 1시간 동안 유지

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

kmdb:
  base-url: http://api.koreafilm.or.kr
  service-key: ${KMDB_SERVICE_KEY}

weather:
  api:
    url: https://api.openweathermap.org/data/2.5/weather
    key: ${WEATHER_KEY}

jwt:
  secret: ${JWT_SECRET}

#aws:
#  enabled: true
#  region: ap-northeast-2
#  nlp-instance-id: ${NLP_INSTANCE_ID}
#  startTimeoutSec: 120
#  stopDelayMin: 30

nlp:
  baseUrl: ${NLP_BASEURL}


kakao:
  admin-key: ${KAKAO_ADMIN_KEY}

oauth2:
  redirect-uri: ${OAUTH2_REDIRECT_URI}