spring:
  profiles:
    active: master  # 현재 활성화할 환경을 'master'로 설정 (추후 prod 등 다른 환경을 추가 가능)

  datasource:
    url: jdbc:h2:mem:testdb  # H2 데이터베이스 사용 (메모리 기반)
    driver-class-name: org.h2.Driver  # H2 데이터베이스의 JDBC 드라이버
    username: sa  # 기본 사용자명 (H2 기본값)
    password:  # 기본적으로 비밀번호 없음 (공백 유지)

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  # H2 데이터베이스에 맞는 Hibernate 설정
    hibernate:
      ddl-auto: update  # 개발 환경에서는 'update', 운영 환경에서는 'validate' 사용 권장
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리를 보기 좋게 포맷팅하여 출력
        show_sql: true  # 콘솔에 실행되는 SQL 쿼리 출력 (디버깅용)

  h2:
    console:
      enabled: true  # H2 콘솔 활성화
      path: /h2-console  # H2 웹 콘솔 접속 경로 (http://localhost:8080/h2-console)
      settings:
        web-allow-others: true  # 다른 IP에서도 접속 가능하도록 설정 (로컬 개발 환경에서는 필요 없음)

  mail:
    host: smtp.gmail.com  # Gmail SMTP 서버
    port: 587  # TLS 포트
    username: jisung494@gmail.com  # Gmail 주소 (발신자)
    password: dfmd gdes wzmf syyv  # 앱 비밀번호 (Gmail 설정에서 생성한 전용 비밀번호)
    properties:
      mail:
        smtp:
          auth: true  # 인증 필요
          starttls:
            enable: true  # TLS 사용

springdoc:
  api-docs:
    enabled: true  # Swagger API 문서 활성화
    path: /v3/api-docs  # API 문서의 기본 경로 (http://localhost:8080/v3/api-docs)
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 접속 경로 (http://localhost:8080/swagger-ui.html)
    operationsSorter: method  # API 목록을 HTTP 메서드(GET, POST 등) 기준으로 정렬
    tagsSorter: alpha  # API 태그를 알파벳 순으로 정렬

kmdb:
  base-url: http://api.koreafilm.or.kr
  service-key: 8Z02968DPIVWH3GL5FBO
